name: Publish NuGet package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Pack project
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Publish package to GitHub Packages
        env:
          PAYMENTINT_TOKEN: ${{ secrets.PAYMENTINT_TOKEN }}
        run: |
          dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key $PAYMENTINT_TOKEN --configfile ./nuget.config
